# Site settings
title: Team no.9 Blog
description: Compuetr System Team project template for Jekyll
keywords: sonhyungon, sonwonseop, kimjiwon, hanyougyoung
author: Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
